/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.AdminController;
import javax.swing.JLabel;
import javax.swing.JPanel;
import model.AdminModel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author TUF GAMING
 */
public class AdminHomesView extends javax.swing.JFrame {

    /**
     * Creates new form AdminHomesView
    */
    AdminModel adminModel;
    AdminPanelHomeView adminPanelHomeView; 
    AdminController adminController;
    
    public AdminHomesView(AdminModel adminModel) {
        initComponents();
        this.adminModel = adminModel;
        adminPanelHomeView = new AdminPanelHomeView();
        
        getContentPane().setLayout(new AbsoluteLayout());
        getContentPane().add(jPanel1, new AbsoluteConstraints(0, 0, 1000, 60)); // Gantikan x, y, width, height dengan nilai yang sesuai
        getContentPane().add(jPanel4, new AbsoluteConstraints(0, 60, 180, 640)); // Gantikan x, y, width, height dengan nilai yang sesuai
        getContentPane().add(adminPanelHomeView, new AbsoluteConstraints(180, 60, 790, 590)); // Gantikan x, y, width, height dengan nilai yang sesuai

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblProfile = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMenu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblUsersView = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lblLogoutView = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        lblRecordsView = new javax.swing.JLabel();
        pnlVehicleView = new javax.swing.JPanel();
        lblVehicleView = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblDashboardView = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnlDefaultAdmin = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/userPicture.png"))); // NOI18N
        lblProfile.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(lblProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 40, 40));
        lblProfile.getAccessibleContext().setAccessibleDescription("");

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 5, 3, 50));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Car Rental System");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Welocome Admin");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 20, -1, -1));

        lblMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/menu.png"))); // NOI18N
        lblMenu.setVerifyInputWhenFocusTarget(false);
        jPanel1.add(lblMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 15, 40, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 60));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/appLogo.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 80, 80));

        jPanel6.setBackground(new java.awt.Color(51, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblUsersView.setBackground(new java.awt.Color(251, 251, 251));
        lblUsersView.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblUsersView.setForeground(new java.awt.Color(251, 251, 251));
        lblUsersView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dataUserNonActive.png"))); // NOI18N
        lblUsersView.setText("Manage Users");
        jPanel6.add(lblUsersView, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 130, -1));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 180, 40));

        jPanel9.setBackground(new java.awt.Color(51, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogoutView.setBackground(new java.awt.Color(251, 251, 251));
        lblLogoutView.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblLogoutView.setForeground(new java.awt.Color(251, 251, 251));
        lblLogoutView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/LogOut.png"))); // NOI18N
        lblLogoutView.setText("Log Out");
        jPanel9.add(lblLogoutView, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 130, -1));

        jPanel4.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 180, 40));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRecordsView.setBackground(new java.awt.Color(251, 251, 251));
        lblRecordsView.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblRecordsView.setForeground(new java.awt.Color(251, 251, 251));
        lblRecordsView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashboard.png"))); // NOI18N
        lblRecordsView.setText("View Records");
        jPanel8.add(lblRecordsView, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 130, -1));

        jPanel4.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 180, 40));

        pnlVehicleView.setBackground(new java.awt.Color(51, 51, 51));
        pnlVehicleView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVehicleView.setBackground(new java.awt.Color(251, 251, 251));
        lblVehicleView.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblVehicleView.setForeground(new java.awt.Color(251, 251, 251));
        lblVehicleView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dataVehicle.png"))); // NOI18N
        lblVehicleView.setText("Manage Vehicle");
        pnlVehicleView.add(lblVehicleView, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 140, -1));

        jPanel4.add(pnlVehicleView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 180, 40));

        jPanel7.setBackground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDashboardView.setBackground(new java.awt.Color(251, 251, 251));
        lblDashboardView.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        lblDashboardView.setForeground(new java.awt.Color(251, 251, 251));
        lblDashboardView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashboard.png"))); // NOI18N
        lblDashboardView.setText("Dashboard");
        jPanel7.add(lblDashboardView, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 5, 140, -1));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 180, 40));

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, 5));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 180, 640));

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, 640));

        javax.swing.GroupLayout pnlDefaultAdminLayout = new javax.swing.GroupLayout(pnlDefaultAdmin);
        pnlDefaultAdmin.setLayout(pnlDefaultAdminLayout);
        pnlDefaultAdminLayout.setHorizontalGroup(
            pnlDefaultAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        pnlDefaultAdminLayout.setVerticalGroup(
            pnlDefaultAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        getContentPane().add(pnlDefaultAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 820, 640));

        setSize(new java.awt.Dimension(1014, 737));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomesView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new AdminHomesView(adminModel).setVisible(true);
            }
        });
    }

    public JLabel getLblVehicleView() {
        return lblVehicleView;
    }

    public void setPnlDefaultAdmin(JPanel pnlDefaultAdmin) {
        this.pnlDefaultAdmin = pnlDefaultAdmin;
    }

    public JPanel getPnlDefaultAdmin() {
        return pnlDefaultAdmin;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public JLabel getLblDashboardView() {
        return lblDashboardView;
    }

    public JLabel getLblLogoutView() {
        return lblLogoutView;
    }

    public JLabel getLblRecordsView() {
        return lblRecordsView;
    }

    public JLabel getLblUsersView() {
        return lblUsersView;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblDashboardView;
    private javax.swing.JLabel lblLogoutView;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblProfile;
    private javax.swing.JLabel lblRecordsView;
    private javax.swing.JLabel lblUsersView;
    private javax.swing.JLabel lblVehicleView;
    private javax.swing.JPanel pnlDefaultAdmin;
    private javax.swing.JPanel pnlVehicleView;
    // End of variables declaration//GEN-END:variables
}
