/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ManagePaymentController;
import javax.swing.table.DefaultTableModel;
import model.CustomerModel;
import model.RentalModel;
import rojerusan.RSTableMetro;

/**
 *
 * @author TUF GAMING
 */
public class CustomerPanelHistoryView extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPanelPaymentView
     */
    CustomerModel customerModel;
    public CustomerPanelHistoryView(CustomerModel customerModel) {
        initComponents();

        this.customerModel = customerModel;
        
        String query = "SELECT j.name, i.id_rental, "
        + "i.price, i.id_vehicle, "
        + "i.start_rental, "
        + "i.end_rental, "
        + "i.returned_date "
        + "FROM rental i "
        + "INNER JOIN users j ON i.id_user = j.id_user WHERE j.id_user = '" + customerModel.getId() + "'";
        System.out.println(customerModel.getId());

//        ManagePaymentController controller = new ManagePaymentController(this, customerModel, model);
            setHistoryPaymentDetailToTable(query);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void setHistoryPaymentDetailToTable(String query){
        RentalModel rentalModel = new RentalModel(0, 0, "", "", "", "", "");
        RentalModel[] rental = rentalModel.putAllData(query, String.valueOf(customerModel.getId()));

        int i=0;
        int price, id_rental;
        String id_vehicle, start_rental, end_rental,  return_date;

        while(i < rental.length){
            id_rental = rental[i].getId_rental();
            price = rental[i].getPrice();
            id_vehicle = rental[i].getId_vehicle();
            start_rental = rental[i].getStart_rental();
            end_rental = rental[i].getEnd_rental();
            return_date = rental[i].getReturn_date();
            if(return_date == null){
                return_date = "Still borrowed";
            }
            Object[] obj = {id_rental, id_vehicle, start_rental, end_rental, return_date, price};
            DefaultTableModel model = (DefaultTableModel)getTblHistoryDetail().getModel();
            model.addRow(obj);
            i++;
        }
    }

    public RSTableMetro getTblHistoryDetail() {
        return tblHistoryDetail;
    }

    public void setTblHistoryDetail(RSTableMetro tblHistoryDetail) {
        this.tblHistoryDetail = tblHistoryDetail;
    }
    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblHistoryDetail = new rojerusan.RSTableMetro();
        jLabel19 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(790, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHistoryDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Rental", "Id Vehicle", "Start Rental", "End Rental", "Return Date", "Price"
            }
        ));
        tblHistoryDetail.setColorBordeFilas(new java.awt.Color(0, 112, 192));
        tblHistoryDetail.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 10)); // NOI18N
        tblHistoryDetail.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        tblHistoryDetail.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        tblHistoryDetail.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblHistoryDetail.setRowHeight(20);
        jScrollPane3.setViewportView(tblHistoryDetail);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 730, 580));

        jLabel19.setFont(new java.awt.Font("Exotc350 Bd BT", 1, 24)); // NOI18N
        jLabel19.setText("HISTORY PAYMENT");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane3;
    private rojerusan.RSTableMetro tblHistoryDetail;
    // End of variables declaration//GEN-END:variables
}
