/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AdminController;
import javax.swing.JButton;
import javax.swing.JPanel;
import model.AdminModel;
import model.CustomerModel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author danie
 */
public class CustomerHomeView extends javax.swing.JFrame {

    /**
     * Creates new form CarsView
     */
    
    CustomerModel customerModel;
    CustomerPanelCarsView customerPanelCarsView; 
    public CustomerHomeView(CustomerModel customerModel) {
        initComponents();
        this.customerModel = customerModel;
        
        customerPanelCarsView = new CustomerPanelCarsView(customerModel);
        
        getContentPane().setLayout(new AbsoluteLayout());
        getContentPane().add(jPanel3, new AbsoluteConstraints(0, 0, 210, 700));
        getContentPane().add(customerPanelCarsView, new AbsoluteConstraints(210, 0, 790, 700)); 
        System.out.print(customerModel.getId());
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }
    
    public JButton getBtnHistory() {
        return btnHistory;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public JButton getBtnList() {
        return btnList;
    }

    public JButton getBtnReturn() {
        return btnReturn;
    }

    public JPanel getPnlDefaultAdmin() {
        return pnlDefaultAdmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        btnReturn = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        pnlDefaultAdmin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setPreferredSize(new java.awt.Dimension(210, 700));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Exotc350 Bd BT", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("System");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 90, 60));

        jLabel18.setFont(new java.awt.Font("Exotc350 Bd BT", 3, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Car Rental ");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 130, 60));

        btnLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnLogout.setText("Log Out");
        jPanel3.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 180, 40));

        btnList.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnList.setText("Vehicle List");
        jPanel3.add(btnList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 40));

        btnReturn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReturn.setText("Returned Vehicle");
        jPanel3.add(btnReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 180, 40));

        btnHistory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnHistory.setText("History Payment");
        jPanel3.add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 180, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 700));

        pnlDefaultAdmin.setPreferredSize(new java.awt.Dimension(790, 700));
        pnlDefaultAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pnlDefaultAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 790, 700));

        setSize(new java.awt.Dimension(1014, 737));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnReturn;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnlDefaultAdmin;
    // End of variables declaration//GEN-END:variables
}
