/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author TUF GAMING
 */
public class CustomerPanelPaymentView extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPanelPaymentView
     */
    public CustomerPanelPaymentView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblVehicleDetail = new rojerusan.RSTableMetro();
        jLabel19 = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(790, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVehicleDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "License", "Name", "Quantiity", "Price", "Description", "Categories", "Rental"
            }
        ));
        tblVehicleDetail.setColorBordeFilas(new java.awt.Color(0, 112, 192));
        tblVehicleDetail.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 10)); // NOI18N
        tblVehicleDetail.setFuenteFilas(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        tblVehicleDetail.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        tblVehicleDetail.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tblVehicleDetail.setRowHeight(20);
        jScrollPane3.setViewportView(tblVehicleDetail);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 730, 580));

        jLabel19.setFont(new java.awt.Font("Exotc350 Bd BT", 1, 24)); // NOI18N
        jLabel19.setText("HISTORY PAYMENT");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel19;
    private javax.swing.JScrollPane jScrollPane3;
    private rojerusan.RSTableMetro tblVehicleDetail;
    // End of variables declaration//GEN-END:variables
}
